{% set name = "astromodels" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#  git_url: https://github.com/threeml/{{ name }}.git
  path: ../../

requirements:
  build:
    - {{ compiler('c') }} # [linux]
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('fortran') }} # [linux]
    - xspec-modelsonly
    - cfitsio
    - ccfits
    - wcslib

  host:
    - python
    - setuptools
    - pip
    - numpy
    - pyyaml>=5.1
    - pandas>=0.23
    - cfitsio
    - ccfits
    - wcslib
    - xspec-modelsonly
    - future
    - numba>=0.54
    - h5py
    - omegaconf
    
  run:
    - python
    - numpy
    - pyyaml>=5.1
    - astropy
    - pytables
    - pandas>=0.23
    - dill
    - cfitsio
    - ccfits
    - wcslib
    - future
    - numba>=0.54
    - h5py
    - interpolation>=2.2.2
    - colorama
    - omegaconf
    - rich
    
build:
  script: python -m pip install --verbose --no-deps --ignore-installed .
  skip: true  # [win]
#  skip: true  # [py3k]

#test:
#  # Python imports
#  imports:
#    - astromodels
#    - astromodels.core
#    - astromodels.functions
#    - astromodels.functions.dark_matter
#    - astromodels.sources
#    - astromodels.utils
#    - astromodels.xspec

#  commands:
#    - pytest -vv --pyargs {{ name }}

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

#  requires:
#    - xspec-modelsonly


about:
  home: https://github.com/threeml/astromodels
  license: UNKNOWN
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
