name: test_env

channels:
  - conda-forge
  - xspecmodels
  - defaults
  
dependencies:
  - python
  - mkl
  - numpy
  - pyyaml>=5.1
  - astropy
  - scipy
  - numdifftools
  - hdf5
  - pytables
  - pandas>=0.23
  - dill
  - cfitsio
  - ccfits
  - wcslib
  - future
  - xspec-modelsonly==6.30.1
  - numba<0.59
  - h5py
  - interpolation>=2.2.3
  - libgfortran
  - omegaconf
  - colorama
  - rich
  - joblib
